#region RDIFramework.NET-generated
//------------------------------------------------------------------------------
//	RDIFramework.NET，是基于.NET的快速信息化系统开发、整合框架，给用户和开发者最佳的.Net框架部署方案。
//	RDIFramework.NET平台包含基础公共类库、强大的权限控制、模块分配、数据字典、自动升级、各商业级控件库、工作流平台、代码生成器、开发辅助
//工具等，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子功能模块按照业务功能组织成单独的程序集文
//件，各子系统开发完成后，由RDIFramework.NET平台进行统一的集成部署。
//
// 框架官网：http://www.rdiframework.net/
// 框架博客：http://blog.rdiframework.net/
// 交流QQ：406590790 
// 邮件交流：406590790@qq.com
// 其他博客：
//      http://www.cnblogs.com/huyong 
//      http://blog.csdn.net/chinahuyong
//------------------------------------------------------------------------------
// <auto-generated>
//	此代码由RDIFramework.NET平台代码生成工具自动生成。
//	运行时版本:4.0.30319.1
//
//	对此文件的更改可能会导致不正确的行为，并且如果
//	重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;

namespace RDIFramework.BizLogic
{
    using RDIFramework.BizLogic;
    using RDIFramework.Utilities;

    /// <summary>
    /// testdemoEntity
    /// 
    /// 
    /// 修改纪录
    /// 
    /// 2018-04-18 版本：1.0  创建主键。
    /// 
    /// 版本：1.0
    /// 
    /// <author>
    /// <name></name>
    /// <date>2018-04-18</date>
    /// </author>
    /// </summary>
    [Serializable]
    public partial class testdemoEntity : BaseEntity
    {
        private int? _id = null;
        /// <summary>
        /// id
        /// </summary>
        public int? Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }

        private String _name = string.Empty;
        /// <summary>
        /// name
        /// </summary>
        public String Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }

        private String _tel = string.Empty;
        /// <summary>
        /// tel
        /// </summary>
        public String Tel
        {
            get
            {
                return _tel;
            }
            set
            {
                _tel = value;
            }
        }

        private String _addr = string.Empty;
        /// <summary>
        /// addr
        /// </summary>
        public String Addr
        {
            get
            {
                return _addr;
            }
            set
            {
                _addr = value;
            }
        }

        private String _idcard = string.Empty;
        /// <summary>
        /// idcard
        /// </summary>
        public String Idcard
        {
            get
            {
                return _idcard;
            }
            set
            {
                _idcard = value;
            }
        }

        private int? _dellog = null;
        /// <summary>
        /// dellog
        /// </summary>
        public int? Dellog
        {
            get
            {
                return _dellog;
            }
            set
            {
                _dellog = value;
            }
        }

        /// <summary>
        /// 构造函数
        /// </summary>
        public testdemoEntity()
        {
        }


        /// <summary>
        /// 从数据行读取
        /// </summary>
        /// <param name="dataRow">数据行</param>
        protected override BaseEntity GetFrom(IDataRow dataRow)
        {
            this.Id = BusinessLogic.ConvertToNullableInt(dataRow[testdemoTable.FieldId]);
            this.Name = BusinessLogic.ConvertToString(dataRow[testdemoTable.FieldName]);
            this.Tel = BusinessLogic.ConvertToString(dataRow[testdemoTable.FieldTel]);
            this.Addr = BusinessLogic.ConvertToString(dataRow[testdemoTable.FieldAddr]);
            this.Idcard = BusinessLogic.ConvertToString(dataRow[testdemoTable.FieldIdcard]);
            this.Dellog = BusinessLogic.ConvertToNullableInt(dataRow[testdemoTable.FieldDellog]);
            return this;
        }
    }
}
